### ISSUE TITLE
[Bug]: A user with special permissions creates a database without showing the name of the bound project

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#1093]
### ODC version

ODC 4.2.3

### OB version

-

### What happened?

![image](https://github.com/oceanbase/odc/assets/46598871/a67d5d97-1d27-4034-9d4e-845c2e6c0ab5)
A user has administrative rights for a data source, but does not have dba rights for the project to which the data source is bound, and the project name is not presented when the database is created.

### What did you expect to happen?

Show the  name of the project.

### How can we reproduce it (as minimally and precisely as possible)?

test_user:tonghan_participate
test_data sourece:oracle4.2.1.0

**Comment by smallsheeeep** [comment]
Since the support for requesting project permissions, the basic information (ID and name) of all projects in the organization is visible to all users.
When creating a new data source, the project name is not displayed if the current user is not a member of the project. A possible solution is to use the interface `GET /api/v2/collaboration/projects/basic` to query the basic information of all projects under the current organization for display.

**Comment by tonghan-gsh** [comment]
![image](https://github.com/oceanbase/odc/assets/46598871/5355d52f-e34e-467a-9abb-c4bf9d5040d7)
pass
