### ISSUE TITLE
[Bug]: Database change execution scheduled task, displaying as terminated

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#1231]
### ODC version

odc423

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/d9e14918-0a84-4d56-90db-2bce3bec3d8f)

### What did you expect to happen?

Normal execution

### How can we reproduce it (as minimally and precisely as possible)?

Database change execution scheduled task

**Comment by smallsheeeep** [comment]
Cannot reproduced yet.

**Comment by smallsheeeep** [comment]
It works for me:
<img width="713" alt="image" src="https://github.com/oceanbase/odc/assets/84772536/cead55cc-b672-404e-a8de-32cfe9424bb0">
The reason for your problem may be that the time of the environment of the ODC you are using has been modified, so that the time of the timer execution is less than the time of the application, so it is directly displayed as "Terminated".
