### ISSUE TITLE
[Bug]: Execution of sql containing rare words failed

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#1346]
### ODC version

ODC 4.2.3

### OB version

OB 4.2.1.3

### What happened?

Execution of sql statement containing rare words in sql window fails.Checking the log, the error message is that inserting data into the operation record failed.
![image](https://github.com/oceanbase/odc/assets/46598871/83a66b28-8dad-452d-abd8-4a23f73f301a)
![image](https://github.com/oceanbase/odc/assets/46598871/fda5751a-cdf0-4ab9-ad40-e2bef13499b1)

### What did you expect to happen?

execution succeed.

### How can we reproduce it (as minimally and precisely as possible)?

drop table  `t_luanma`;
CREATE TABLE `t_luanma` (
  `name` varchar(30) DEFAULT NULL
) DEFAULT CHARSET = utf8mb4;

insert into `t_luanma` values('a'),('b');
update t_luanma set name='𪩘𪾢𫄧2' limit 1;
update t_luanma set name='𨱑𨱔𨺙2' where name!='𪩘𪾢𫄧2';

**Comment by MarkPotato777** [comment]
This issue is related to the table `audit_event` in ODC metadb. When executing a SQL, ODC will record this SQL in `audit_event`. However, in this test case, `audit_event`'s character_set is set to GBK as we don't explicitly set default charset while creating the table and the `character_set_server` variable is GBK, so while inserting a rare word in the format of utf8 into a GBK table, the observer will return an error 'Incorrect String value'. If the `audit_event`'s charset is utf8, this problem is resolved.

Two actions:
- optimize audit module exception handling. Do not let audit block the main business process;
- optimize the doc of deployment: ODC metadb charset to be set to utf8mb4 is a requirement;

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/5bb988d7-e916-48e7-b653-4354cdcf294e)



![Image](https://github.com/oceanbase/odc/assets/143492234/ff822ece-af3e-4673-8a2e-0cb4804a3cf7)

pass
