### ISSUE TITLE
[Bug]: Database change execution failed

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#1483]
### ODC version

odc423

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/150df52c-182b-4b2d-9a0b-0c6eae41b0ce)
![image](https://github.com/oceanbase/odc/assets/143492234/60540b4a-e903-4797-95d0-c89263878a6e)

### What did you expect to happen?

Database change execution successful

### How can we reproduce it (as minimally and precisely as possible)?

Execute database changes

**Comment by smallsheeeep** [comment]
Sorry, I can not reproduce your problem. It works for me:
<img width="738" alt="image" src="https://github.com/oceanbase/odc/assets/84772536/53df4276-0718-4f25-a879-414c95cc1c1d">
I wonder your datasource has some exception, error occur when I create a session:
<img width="366" alt="image" src="https://github.com/oceanbase/odc/assets/84772536/3ab9af75-a901-463a-8253-03bf2f657af8">

**Comment by smallsheeeep** [comment]
I cannot reproduce your problem:
<img width="738" alt="image" src="https://github.com/oceanbase/odc/assets/84772536/83758a8f-a725-491f-8d78-34a43940f634">
May the datasource has some exception, since error when I create a session:
<img width="366" alt="image" src="https://github.com/oceanbase/odc/assets/84772536/47efe5be-a565-4486-8fdd-4706cd5c5107">

**Comment by sl01388797** [comment]
The problem disappears
