### ISSUE TITLE
[Bug]: test connection success but open sql console result in 404 error

### ISSUE THREAD

**Issue by yizhouxw** [oceanbase/odc#1828]
### ODC version

4.2.3

### OB version

not related

### What happened?

 test connection success but open sql result in 404 error

### What did you expect to happen?

open sql console should not got 404 error

### How can we reproduce it (as minimally and precisely as possible)?

N/A

**Comment by yhilmare** [comment]
QAer may not consider of this.

ODC will encode some information into session id, just like database_id, datasource_id and etc. our encoder is base64 encoder, some special character will be encoded to '/', just like this:
![截屏2024-03-11 11 59 00](https://github.com/oceanbase/odc/assets/22992296/2c3b6b95-29aa-48c0-8d27-d3e66be3c43e)

but '/' is not expected, so that we change another url safe encoder to avoid this problem~
