### ISSUE TITLE
[Bug]: CAS redirect URL is http while the actual is https

### ISSUE THREAD

**Issue by smallsheeeep** [oceanbase/odc#210]
### ODC version

4.2.0

### OB version

Regardless of OB version

### What happened?

CAS redirect URL is http while the actual is https:
<img width="1502" alt="image" src="https://github.com/oceanbase/odc/assets/84772536/946ce38d-0089-4d14-aee4-637b432d1a4c">

### What did you expect to happen?

The CAS redirect URL should be https

### How can we reproduce it (as minimally and precisely as possible)?

<null>

**Comment by ungreat** [comment]
Typically, this is caused by the use of load balancing.The host used by ODC's redirectUrl is determined by the request to the ODC server.The load balancer listens on the HTTPS port and redirect the request to the ODC using HTTP，may result in a different protocol for the redirect url.
In this case,  you can specify odc site url by changing the record of the `config_system_configuration` table, which key is `odc.site.url`.Note that this value cannot contain localhost, otherwise it will not take effect.

**Comment by ungreat** [comment]
Typically, this is caused by the use of load balancing.The host used by ODC's redirectUrl is determined by the request to the ODC server.The load balancer listens on the HTTPS port and redirect the request to the ODC using HTTP，may result in a different protocol for the redirect url.
In this case,  you can specify odc site url by changing the record of the `config_system_configuration` table, which key is `odc.site.url`.Note that this value cannot contain localhost, otherwise it will not take effect.

**Comment by Huangxiao-mas** [comment]
passed
