### ISSUE TITLE
[Bug]: The error message is not useful when the project name is modified repeatedly

### ISSUE THREAD

**Issue by zijiacj** [oceanbase/odc#2438]
### ODC version

odc423

### OB version

not related

### What happened?

The error message is not useful when the project name is modified repeatedly
<img width="899" alt="image" src="https://github.com/oceanbase/odc/assets/135618909/2f03295a-9c4c-4b6a-8414-46b191a34cb4">

### What did you expect to happen?

Give helpful hints, such as that 'the project name already exists and cannot be changedGive helpful hints'

### How can we reproduce it (as minimally and precisely as possible)?

Archive project A, and then change the project name of existing project B to the name of archived project A

**Comment by qymsummer** [comment]
![Image](https://github.com/oceanbase/odc/assets/40919496/2805d066-bb35-4fe0-8a9a-2029301bcbb1)

When editing a project, only the description information is modified without changing the name. It prompts "Project named qym already exists, please modify and try again". This bug is reopened and a new bug needs to be submitted. After the new bug is verified, verify whether the "Access Metadatabase Error" is still reported.

**Comment by qymsummer** [comment]
![Image](https://github.com/oceanbase/odc/assets/40919496/4f7e526d-7c44-40cb-83b1-a85e0088b517)

pass

**Comment by qymsummer** [comment]
![Image](https://github.com/oceanbase/odc/assets/40919496/4f7e526d-7c44-40cb-83b1-a85e0088b517)

pass
