### ISSUE TITLE
[Bug]: Multiple nodes access ODC , and the pre-check results cannot be viewed in task details

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#2724]
### ODC version

ODC430

### OB version

independent

### What happened?

Multiple nodes access ODC through domain names, and the pre-check results cannot be viewed in task details
![image](https://github.com/oceanbase/odc/assets/59468957/e7196fc7-21ad-4525-8a45-bec86f7c415a)
![image](https://github.com/oceanbase/odc/assets/59468957/bd7c1dc4-4193-4abd-9095-6e04d7807238)

### What did you expect to happen?

can view it

### How can we reproduce it (as minimally and precisely as possible)?

chat privately

**Comment by yhilmare** [comment]
the root cause is that the type reference is wrong the request is dispatched into other machine~

and I fixed this:

**Comment by yhilmare** [comment]
this issue is not related to the domain, we can reproduce it by following steps:
1. prepare multi-nodes odc cluster.
2. start a task on a odc node, we call it A.
3. attempt to view the sql-check result and request node B, thus the node B will dispatch this request to A and we can reproduce the issue~
