### ISSUE TITLE
[Bug]: SQL console specifications have not taken effect after modifying

### ISSUE THREAD

**Issue by smallsheeeep** [oceanbase/odc#775]
### ODC version

4.2.1

### OB version

null

### What happened?

![image](https://github.com/oceanbase/odc/assets/84772536/5bc3eea1-5518-4155-b84e-64176c312f1f)
![image](https://github.com/oceanbase/odc/assets/84772536/bf3fc504-326a-48b6-b4c9-2b75ec337ac0)

### What did you expect to happen?

.

### How can we reproduce it (as minimally and precisely as possible)?

.

### Anything else we need to know?

.

### Cloud

.

**Comment by yhilmare** [comment]
The direct reason of this issue is that the type of the `desc xxx` is recognized as `EXPLAIN`. I look up the g4 file and find out that explain is the synonym of the desc and that is to say that `desc xxx` can be written as `explain xxx` that has the same meaning.

I suggest that it is unnecessary to distinguish between desc and explain.

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/fdd1a930-9142-4148-9f12-d2462e530c21)

PASS
